### ISSUE TITLE
Session / authenticated access

### ISSUE THREAD

**Issue by eirikhm** [arguseyes/argus-eyes#13]
Interesting project! Do you support any cookie / session state for signing in to websites?

**Comment by branneman** [comment]
Not yet, but we're thinking of adding a `user-script` option on multiple levels, that would solve your usecase. See also: #12

**Comment by branneman** [comment]
Since [v0.6.0](https://github.com/arguseyes/argus-eyes/releases/tag/v0.6.0) it's possible to specify HTTP Basic Authentication credentials in your config file, see documentation for more info: http://arguseyes.io/reference.html#credentials

Specifying PhantomJS flags was also added, which gives you the option to store cookies which might solve your usecase too: http://arguseyes.io/reference.html#phantomjs-flags

Lastly, you should take a look at the new [wait-for-script](http://arguseyes.io/reference.html#wait-for-script) and [run-script](http://arguseyes.io/reference.html#run-script) options, those might be of help as well.

Closing this issue as resolved.
