### ISSUE TITLE
Support configurable PhantomJS timeout

### ISSUE THREAD

**Issue by rarkins** [arguseyes/argus-eyes#20]
It would be useful if the hardcoded figure of 10s could be made configurable.

**Comment by branneman** [comment]
Could you describe your usecase? Why isn't 10 seconds enough? I myself can't imagine (yet) why you would need more time.

**Comment by rarkins** [comment]
I'm not sure exactly why it takes so long at times, but it does (only one page, which is really long - asynchronously loads things like Google Maps directions, authentication/customisation, etc). Right now we just monkey patched it to 30s to solve all problems. I didn't see it happening on our CI platform, however it was happening regularly when run in the dev environment - something about it (virtualisation overhead, etc) perhaps at fault. The site has a pagespeed score of around 80-90 and is fairly good according to webpagetest (uses critical CSS, progressive loading, etc).

**Comment by lazytesting** [comment]
As some DEV environments can be slow due to limited resources and application/cache warmup time I agree that it should be configurable. Because it is environment specific we should use a CLI parameter for it.

**Comment by isaacviel** [comment]
Agreed with @lazytesting and @rarkins. Unfortunately our dev environment can be quite slow and is never particularly consistent. I've had to manually change the `10 * 1000` timeout to `30 * 1000` in `phantomjs-script.js`'s `setTimeout(function()` in order to work successfully with our dev environment. Thanks for consideration and work on this tool. It's been great!
