### ISSUE TITLE
Saved 0 screenshots in: .argus-eyes/homepage

### ISSUE THREAD

**Issue by romainl** [arguseyes/argus-eyes#7]
Hi, I have troubles getting argus-eyes to work.

The `.argus-eyes/homepage/` directory is created but no screenshot is generated. Would it be an argus-eyes issue or a phantomjs issue?

Environment:

    Mac OS X   10.10.5
    node       5.5.0
    npm        3.73
    phantomjs  2.1.1 (installed globally via `$ npm install -g phantomjs`)
    argus-eyes 0.4.0 (installed globally via `$ npm install -g argus-eyes`)

Config file:

    {
      "sizes": ["1280x768"],
      "pages": [ {
          "name": "homepage",
          "url": "http://johncoltrane.tumblr.com/",
          "components": [ "sidebar" ]
        }],
      "components": [ {
          "name": "sidebar",
          "selector": "#side"
        }]
    }

Command used:

    $ argus-eyes add homepage --verbose

Full output:

    [verbose] Found 1 size, 1 page and 1 component
    [verbose] Taking screenshot with PhantomJS for image: '1280x768/homepage/sidebar.png'
    PhantomJS errored for file: '.argus-eyes/homepage/1280x768/homepage/sidebar.png'
    [verbose]  {"code":"ENOENT","errno":"ENOENT","syscall":"spawnSync null","path":null,"spawnargs":["/usr/local/lib/node_modules/argus-eyes/app/phantomjs-script.js","http://johncoltrane.tumblr.com/","/Users/lafourcade/Documents/argus-eyes/.argus-eyes/homepage/1280x768/homepage/sidebar.png","1280x768","#side","[]","return true"]}
    Saved 0 screenshots in: .argus-eyes/homepage

Note:

Creating the full directory structure manually with

    $ mkdir -p .argus-eyes/homepage/1280x768/homepage

didn't help.

**Comment by branneman** [comment]
It is not necessary to install phantomjs yourself, it comes bundled as a dependency with argus-eyes, as you can see here: [package.json#L46](https://github.com/arguseyes/argus-eyes/blob/master/package.json#L46)

But since the `path` variable is `null` in your error, it seems it cannot find this locally installed phantomjs. Argus Eyes tries to execute the locally installed phantomjs, which seems to be going wrong somehow. There were no warnings during the global installation of argus-eyes?

Could you create a `test.js` file with this contents in a different folder:
```js
var execFileSync = require('child_process').execFileSync;
var phantomPath = require('phantomjs-prebuilt').path;

console.log(phantomPath);
console.log(execFileSync(phantomPath, ['-v'], { encoding: 'utf8' }));
```

Then please run these commands inside that folder:
```
$ npm install phantomjs-prebuilt
$ node test.js
```

It should output the location of the phantomjs binary and ask for it's version. If this is going wrong somehow, it's a phantomjs bug, specific to your environment. If this does work however, it's probably an error somewhere in argus-eyes.

**Comment by romainl** [comment]
Thanks, this the output of `$ node test.js` in a different directory:

    /Users/lafourcade/Desktop/testargus/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs
    2.1.1

The output is similar in the same directory as in my original comment.

**Comment by branneman** [comment]
Hmm ok, strange. Any more info you can give me? For example, did you install argus-eyes with 'sudo'? Does it help to add sudo before the argus-eyes command?

I can't reproduce your situation, I've installed your versions of node and phantom, the only difference now is that I'm using OSX 10.11.3

Something else you could try, is run the argus-eyes tests:
```
cd /usr/local/lib/node_modules/argus-eyes/
npm install
npm test
```
Are all the **add** tests failing?

**Comment by romainl** [comment]
`/usr/local/lib/node_modules/argus-eyes/node_modules` had not been created during the global install so it logically failed to find its dependencies. Removing argus-eyes and re-installing it with `sudo` solved the issue.

Argus-eyes seems to work, now. Thank you.

**Comment by branneman** [comment]
Ah, ok. For future reference, what was the output of the `npm install` command without sudo? Did that give you any indication of a failing or incomplete install?

**Comment by romainl** [comment]
I'm sorry but I don't remember anything special. IIRC, `$ npm install argus-eyes` didn't complain about anything.
